Server:
  Port: 8081
Spring:
  Security:
    oauth2:
      client:
        registration:
          google:
            clientId: 516084187871-vl2driou4kgeubil0hcpgca13ui362kn.apps.googleusercontent.com
            clientSecret: C57JBiuMbCnjna5xhNqO7OE3
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/feri
    username: root
    password: qqwwee
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      use-new-id-generator-mappings: false
      ddl-auto: create